#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

for f in tests/tst_*.c; do
    gcc -DWITH_TLD=1 -o $WORKDIR/foo $f tests/utils.c `pkg-config --cflags --libs libidn`
    echo "PASS: gcc $f"
    $WORKDIR/foo
    echo "PASS: run $f"
done

cd $WORKDIR
cat <<EOF > libidntest.c
#include <stringprep.h>

int main(void)
{
  if (!stringprep_check_version (STRINGPREP_VERSION))
    return 1;

  return 0;
}
EOF

gcc -o libidntest libidntest.c `pkg-config --cflags --libs libidn`
echo "PASS: gcc"
[ -x libidntest ]
./libidntest
echo "PASS: run"
man -P cat stringprep_check_version
echo "PASS: man"
